name: "Build LLVM/MLIR"
description: "Build LLVM from source"
author: "MLIR-China"
inputs:
  llvm-src:
    required: true
    description: "llvm source directory"
runs:
  using: "node16"
  main: "dist/index.js"
