name: "Build LLVM/MLIR"
description: "Build LLVM from source"
author: "MLIR-China"
inputs:
  llvm-project-root-dir:
    required: true
    description: "llvm source directory"
  native-llvm-install-dir:
    required: true
    description: "native llvm installation used in cross compiling"
  cmake-args:
    required: false
    description: "cmake arguments"
runs:
  using: "node16"
  main: "dist/index.js"
