name: Auto release

on:
  schedule:
    # every 3 hours
    - cron: "0 */3 * * *"
  push:
    branches:
      - main
      - "releases/*"
jobs:
  generate_id:
    name: Generate ID of release
    runs-on: ubuntu-latest
    outputs:
      formatted_date: ${{ steps.date.outputs.formatted_date }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=formatted_date::$(date +'%Y-%m-%d-%H%M')"
  release: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.job.os }}
    needs: [generate_id]
    strategy:
      fail-fast: false
      matrix:
        build-type: ["Release", "MinSizeRel"]
        job:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04 }
    steps:
      - name: Set Swap Space
        if: ${{ startsWith(runner.os, 'Linux') }}
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Checkout llvm/llvm-project
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: main
      - uses: MLIR-China/stage@main
        with:
          llvm-project-root-dir: llvm-project
          cmake-args: |
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
      - name: Zip the installation
        id: zip
        run: |
          ARCHIVE_PATH=$(pwd)/llvm-install-${{ matrix.build-type }}.zip
          cd $HOME/llvm-install
          zip -r ${ARCHIVE_PATH} .
          echo ::set-output name=ARCHIVE_PATH::${ARCHIVE_PATH}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.zip.outputs.ARCHIVE_PATH }}
          tag_name: nightly-tag-${{ needs.generate_id.outputs.formatted_date }}
