name: "Build and release"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
concurrency:
  group: stage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  generate_id:
    name: Generate ID of release
    runs-on: ubuntu-latest
    outputs:
      formatted_date: ${{ steps.date.outputs.formatted_date }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=formatted_date::$(date +'%Y-%m-%d-%H%M')"
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.job.os }}
    needs: [generate_id]
    strategy:
      fail-fast: false
      matrix:
        build-type: ["Debug", "Release", "RelWithDebInfo", "MinSizeRel"]
        job:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04 }
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: |
          sudo apt install -y ccache
      - name: Checkout llvm/llvm-project
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: main
      - uses: ./
        with:
          llvm-project-root-dir: llvm-project
          cmake-args: |
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
      - name: Zip the installation
        id: zip
        run: |
          ARCHIVE_PATH=$(pwd)/llvm-install-${{ matrix.build-type }}.zip
          cd $HOME/llvm-install
          zip -r ${ARCHIVE_PATH} .
          echo ::set-output name=ARCHIVE_PATH::${ARCHIVE_PATH}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.zip.outputs.ARCHIVE_PATH }}
          tag_name: nightly-tag-${{ needs.generate_id.outputs.formatted_date }}
